name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [2.1.0, 2.1.2]
    env:
      repo: "govpf/pgsync"
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Clone pgsync
      run: git clone -b ${{ matrix.versions }} https://github.com/toluaina/pgsync

    - name: Build
      uses: docker/build-push-action@v6.0.0
      with:
        context: ./pgsync
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}
